---

- hosts: all
  become: true
  roles:
    - common

- hosts: slave
  become: true
  roles:
    - slave

- hosts: master
  become: true
  roles:
    - master

- name: restart master
  become: true
  hosts: master
  tasks:
    - command: systemctl restart named

- name: add domain
  become: true
  hosts: slave
  roles:
    - dns-client

- name: install nginx
  become: true
  hosts: slave
  roles:
    - nginx

- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    ansible_become_pass: UserPassword # your user password
  tasks:
    - name: resolv.conf
      lineinfile: dest=/etc/resolv.conf
                  line='nameserver {{ hostvars['master'].ansible_ssh_host }}'
                  state=present 

